### ISSUE TITLE
Ubuntu Mate 16.04: Can not close "Calf JACK Host" without cutting out audio

### ISSUE THREAD

**Issue by ghost** [M4he/Linux#1]
Is there any possible way to minimize the Calf JACK Host window to my notifications area? I'm a bit of a minimalist, and I would still like to be able to hear my music (and the rest of my system) without it taking up space in my Windows List.

**Comment by talkaboom** [comment]
Crossing it out (not quitting) removes any tab and only the icon in the notification area stays active. Your problem seems to be more of how you configured your panels maybe? I am using nearly stock XFCE with xubuntu (16.04), not mate, so maybe I should not have posted...
